### ISSUE TITLE
查询结果显示问题

### ISSUE THREAD

**Issue by GRFTSOL** [Karmenzind/kd#31]
同该[issue](https://github.com/Karmenzind/kd/issues/28#issue-2279841946)
![图片](https://github.com/user-attachments/assets/53ecdca7-1da8-477f-b7a2-ad05e7474b54)

```
OS: Arch Linux x86_64
Host: Windows Subsystem for Linux - Arch (2.2.4)
Kernel: Linux 5.15.153.1-microsoft-standard-WSL2
Uptime: 11 hours, 49 mins
Packages: 181 (pacman)
Shell: fish 3.7.1
Display (rdp-0): 2560x1440 @ 60Hz
WM: WSLg (Wayland)
Terminal: xterm-256color
```
更换pager为bat后正常

**Comment by Karmenzind** [comment]
Noted with thanks.

**Comment by Karmenzind** [comment]
有点好奇如果你安装一个win版本，在wsl中调用kd.exe会是什么效果

**Comment by GRFTSOL** [comment]
> 有点好奇如果你安装一个win版本，在wsl中调用kd.exe会是什么效果

![图片](https://github.com/user-attachments/assets/1849c330-753a-49cc-bdb3-b24ffeb217ed)
他是正常的....

**Comment by Karmenzind** [comment]
> > 有点好奇如果你安装一个win版本，在wsl中调用kd.exe会是什么效果
> 
> 
> 
> ![图片](https://github.com/user-attachments/assets/1849c330-753a-49cc-bdb3-b24ffeb217ed)
> 
> 他是正常的....

哦想起来了，win版本我默认关掉了paging，因为win基本没什么可用的pager

**Comment by Karmenzind** [comment]
@GRFTSOL Hi，可否帮忙测试下，配置文件中把pager_command改成⬇️这样之后显示是否正常？我这里复现不了
```toml
pager_command = "less -RF"
```

**Comment by Karmenzind** [comment]
我在Ubuntu 20测试了，可以解决颜色乱码

**Comment by GRFTSOL** [comment]
> @GRFTSOL Hi，可否帮忙测试下，配置文件中把pager_command改成⬇️这样之后显示是否正常？我这里复现不了
> 
> ```toml
> pager_command = "less -RF"
> ```

可以, 改为less以后正常了

**Comment by Karmenzind** [comment]
OK，我后续写入默认配置
